# Generated by Django 5.0.1 on 2024-02-02 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Community_Managers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('labour_shortage_activities', models.TextField()),
                ('natural_activities', models.TextField()),
                ('local_activities', models.TextField()),
                ('other_information', models.TextField()),
                ('region', models.TextField()),
                ('genre_tags', models.TextField()),
                ('rewards', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('day_to_day_schedule', models.TextField()),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.quests')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_people', models.IntegerField()),
                ('gender_and_age', models.TextField()),
                ('composition', models.TextField()),
                ('duration_of_stay', models.CharField(max_length=30)),
                ('place_of_birth', models.TextField()),
                ('place_of_residence', models.TextField()),
                ('occupation', models.TextField()),
                ('special_note', models.TextField()),
                ('expectations_for_the_platform', models.TextField()),
                ('concerns', models.TextField()),
                ('identifier', models.OneToOneField(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('application_date', models.DateTimeField()),
                ('approval_status', models.BooleanField()),
                ('community_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.community_managers')),
                ('quest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.quests')),
                ('user_id', models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='backend.users')),
            ],
        ),
    ]
