# Generated by Django 5.0.1 on 2024-02-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_users_email_remove_users_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='duration_of_stay',
        ),
        migrations.RemoveField(
            model_name='users',
            name='special_note',
        ),
        migrations.AddField(
            model_name='applications',
            name='duration_of_stay',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='special_note',
            field=models.TextField(null=True),
        ),
    ]
