# Generated by Django 5.0.1 on 2024-02-05 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_users_duration_of_stay_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number_of_people', models.IntegerField()),
                ('gender_and_age', models.TextField()),
                ('composition', models.TextField()),
                ('place_of_birth', models.TextField()),
                ('place_of_residence', models.TextField()),
                ('occupation', models.TextField()),
                ('expectations_for_the_platform', models.TextField()),
                ('concerns', models.TextField()),
                ('created_by', models.ForeignKey(default=7, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='applications',
            name='user_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='backend.teams'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
